version: '3'
services:
  app:
    build:
      context: .
    image: cspw2s
    container_name: 'cspw2s'
    ports:
      - 2000:2000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: 'mongo'
