version: '3.9'
services:
  app:
    build:
      context: .
    image: cspw2s
    container_name: 'cspw2s'
    restart: on-failure
    ports:
      - 2000:2000
    volumes:
      - ./credentials:/root/.aws/credentials
      - ./config:/root/.aws/config
    depends_on:
      - mongodb
      - steampipe
  mongodb:
    image: mongo
    restart: on-failure
    container_name: 'mongo'
  steampipe:
    image: turbot/steampipe
    container_name: 'steampipe'
    environment:
      STEAMPIPE_DATABASE_PASSWORD: ${SP_PASSWORD}
    restart: on-failure
    volumes:
      - ./credentials:/home/steampipe/.aws/credentials
    command: ['service', 'start', '--foreground']
